module  decoder_nto2n_tb();
  reg  [3:0]a;
  wire [15:0]y;
   decoder_nto2n dut (.a(a),.y(y));
  initial begin
    $monitor("Time=%0t || a=%b || y=%b",$time,a,y);
    a = 4'b0000; #10;
    a = 4'b0001; #10;
    a = 4'b0010; #10;
    a = 4'b0011; #10;
    a = 4'b0100; #10;
    a = 4'b0101; #10;
    a = 4'b0110; #10;
    a = 4'b0111; #10;
    a = 4'b1000; #10;
    a = 4'b1001; #10;
    a = 4'b1010; #10;
    a = 4'b1011; #10;
    a = 4'b1100; #10;
    a = 4'b1101; #10;
    a = 4'b1110; #10;
    a = 4'b1111; #10;
    $finish;
  end
  initial begin
    $dumpfile(" decoder_nto2n.vcd");
    $dumpvars(0, decoder_nto2n_tb);
  end
endmodule
